# Generated by Django 5.2.1 on 2025-06-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('HoF', 'Hall of Fame'), ('Legend', 'Legend')], max_length=10)),
                ('min_value', models.PositiveIntegerField()),
                ('alternative_group', models.PositiveIntegerField(blank=True, help_text='Use same number for OR-requirements', null=True)),
                ('min_height', models.PositiveIntegerField(default=69, help_text="Player height in inches (5'9 = 69)")),
                ('max_height', models.PositiveIntegerField(default=87, help_text="Player height in inches (7'3 = 87)")),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.attribute')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='project.badge')),
            ],
            options={
                'unique_together': {('badge', 'level', 'attribute', 'alternative_group')},
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_levels', models.ManyToManyField(blank=True, to='project.badgelevel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
