# Generated by Django 5.2.1 on 2025-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Player height in inches', null=True),
        ),
    ]
