# Generated by Django 5.2.1 on 2025-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_build_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
