# Generated by Django 5.2.1 on 2025-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_badge_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='description',
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.CharField(default='Shooting', max_length=100),
            preserve_default=False,
        ),
    ]
