# Generated by Django 5.2.1 on 2025-06-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_attribute_description_attribute_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=10)),
                ('w_25_74', models.FloatField()),
                ('w_75_79', models.FloatField()),
                ('w_80_84', models.FloatField()),
                ('w_85_89', models.FloatField()),
                ('w_90_94', models.FloatField()),
                ('w_95_98', models.FloatField()),
                ('w_99', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.attribute')),
            ],
        ),
    ]
