# Generated by Django 5.2.1 on 2025-06-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_attributeweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_source_value', models.IntegerField(help_text='Source value (always 99)')),
                ('obs_dependent', models.IntegerField(help_text='Observed dependent value at source=99')),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps_as_dependent', to='project.attribute')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps_as_source', to='project.attribute')),
            ],
        ),
    ]
