# Generated by Django 5.2.1 on 2025-06-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_attributedependency_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(help_text='Player height in inches (e.g. 87 for 7\'3")')),
                ('cap', models.PositiveIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.attribute')),
            ],
            options={
                'unique_together': {('height', 'attribute')},
            },
        ),
    ]
