# Generated by Django 5.2.4 on 2025-08-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_attributecap'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
