# Generated by Django 5.2.1 on 2025-06-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_statusimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusimage',
            name='status_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_fb.statusmessage'),
        ),
        migrations.AlterField(
            model_name='statusimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.image'),
        ),
    ]
