# Generated by Django 5.2.1 on 2025-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_statusimage_status_message_alter_statusimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='image_file',
        ),
    ]
