# Generated by Django 5.2.1 on 2025-06-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0009_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_sent', to='mini_fb.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_received', to='mini_fb.profile'),
        ),
    ]
